rm -f 2dx_defocus_positions.txt
rm -f 2dx_defocus_select_positions.txt
rm -f 2dx_lencalc-doc.tmp
rm -f 2dx_origtiltk-console.log
rm -f 2dx_origtiltk-reflections.log
rm -f 2dx_peaksearch-amp_before_LHpass.mrc
rm -f 2dx_tiltgeom.out
rm -f 2dx_tiltgeom2.out
rm -rf APH
rm -rf CUT
rm -rf FFTIR
rm -f History.dat
rm -rf LOGS
rm -f ManualMasking-CCmap.mrc
rm -f ManualMasking-UnbendPlot.mrc
rm -rf PS
rm -rf SCRATCH
rm -f TMP.2dx_deftilt.good.out.txt
rm -f auto_1-p1.mrc
rm -f auto_1-profile.dat.gz
rm -f auto_1-unitcells-spider.doc
rm -f auto_1.mtz
rm -f auto_1.raw.mrc
rm -f auto_1.spt
rm -f auto_1.spt.bak
rm -f auto_1_phase_zero-p1.mrc
rm -f auto_1_phase_zero.mtz
rm -f avrg.hk
rm -f avrg.hkl
rm -f centric.hk
rm -f centric.hkl
rm -f centric_phase_zero.hkl
rm -f final_map.mrc
rm -f final_map_FouFilter.mrc
rm -f mtzdump.txt
rm -f peaks_xy.dat
rm -f peaks_xy_final.dat
rm -rf proc
rm -rf PRJ
rm -f labelh.tmp
cp backup/2dx_image.cfg .
